name "application_env"
maintainer "Barry Hoggard"
description "Writes a config/application.yml file with custom ENV values to apps' deploy directories."
version "0.1"
recipe "application_env::configure", "Write a config/application.yml file to app's deploy directory."
